Repository yitianwang18/cse112-s22-group14, pull requests merged in 2022-06, with the labels that each got.

#109 Got rid of close button popping up - Fixed merge conflict issue
  source/v1/js/eventBus.js
Labels: bug

#105 Add C4 Model for our Powelldoro Timer
  specifications/C4-model/Powelldoro_C4_Model.pdf
  specifications/C4-model/c4-model.md
Labels: documentation

#116 theme/reset buttons in settings, update btn sizes
  source/v1/css/colors-forest.css
  source/v1/css/colors-stars.css
  source/v1/css/layout.css
  source/v1/index.html
  source/v1/js/eventBus.js
  source/v1/js/main.js
  source/v1/js/settingsTab.js
  source/v1/js/taskList.js
Labels: enhancement

#126 Fix/jsdoc workflow
  .github/workflows/gen_docs.yml
  docs/EventBus.html
  docs/InstructionsBox.html
  docs/NotificationBox.html
  docs/SettingsTab.html
  docs/Task.html
  docs/TaskDisplay.html
  docs/TaskList.html
  docs/TimerContainer.html
  docs/TimerDisplay.html
  docs/cypress_tests_cypress_plugins_index.js.html
  docs/global.html
  docs/index.html
  docs/js_errorNotificationBox.js.html
  docs/js_eventBus.js.html
  docs/js_instructionsBox.js.html
  docs/js_main.js.html
  docs/js_notify.js.html
  docs/js_settingsTab.js.html
  docs/js_task.js.html
  docs/js_taskDisplay.js.html
  docs/js_taskList.js.html
  docs/js_timer.js.html
  docs/js_timerContainer.js.html
Labels: documentation

#113 added tab highlighting for settings tab
  source/v1/js/settingsTab.js
Labels: enhancement

#112 Reverse safari notification error check box logic
  source/v1/css/layout.css
  source/v1/js/errorNotificationBox.js
  source/v1/js/notify.js
  source/v1/js/settingsTab.js
Labels: enhancement

#128 added welcome pop up, updated reset's long break
  source/v1/css/colors-forest.css
  source/v1/css/colors-stars.css
  source/v1/css/layout.css
  source/v1/index.html
  source/v1/js/eventBus.js
  source/v1/js/main.js
  source/v1/js/settingsTab.js
  source/v1/js/welcomeBox.js
Labels: enhancement

#127 Feature/theme local storage
  source/v1/css/colors-stars.css
  source/v1/js/eventBus.js
  source/v1/js/main.js
  source/v1/js/settingsTab.js
  source/v1/js/timerContainer.js
Labels: enhancement

#131 Feature/focus rings
  source/v1/css/colors-forest.css
  source/v1/css/colors-stars.css
  source/v1/css/layout.css
Labels: enhancement

#132 Fix/error messages
  source/v1/css/colors-stars.css
  source/v1/js/taskList.js
Labels: bug

#110 updated instructions, added icons, added link
  source/v1/assets/img/PowelldoroFav.png
  source/v1/css/colors-forest.css
  source/v1/css/colors-stars.css
  source/v1/css/layout.css
  source/v1/index.html
  source/v1/js/eventBus.js
  source/v1/js/instructionsBox.js
  source/v1/js/main.js
  source/v1/js/settingsTab.js
  source/v1/js/taskList.js
  source/v1/js/timerContainer.js
Labels: bug

#133 Test/settings menu
  source/v1/cypress_tests/cypress/integration/tests/settingsTests.js
  source/v1/cypress_tests/cypress/integration/tests/taskDisplayTests.js
  source/v1/cypress_tests/package-lock.json
  source/v1/cypress_tests/package.json
Labels: enhancement

#134 Feature/add timer container jest tests
  source/v1/jest_tests/EventBus.js
  source/v1/jest_tests/timerContainer.test.js
Labels: enhancement

#135 Fix/remove reset
  source/v1/js/eventBus.js
  source/v1/js/timerContainer.js
Labels: enhancement

#108 Added last week's meeting summaries, standups, and ADRs
  specifications/adrs/0025-number-options-for-customizations.md
  specifications/adrs/0026-customizing-number-of-pomos.md
  specifications/adrs/0027-reset-pomo-button.md
  specifications/adrs/0028-button-layout.md
  specifications/meeting-summaries/05-25-wed.md
  specifications/meeting-summaries/05-29-sun.md
  specifications/standups/05-23-22.md
  specifications/standups/05-24-22.md
  specifications/standups/05-25-22.md
  specifications/standups/05-26-22.md
  specifications/standups/05-27-22.md
  specifications/standups/05-30-22.md
  specifications/standups/05-31-22.md
Labels: documentation

#138 fix hotkeys behaviors and most cypress tests
  package-lock.json
  source/v1/cypress_tests/cypress/integration/tests/errorMessagesTests.js
  source/v1/cypress_tests/cypress/integration/tests/eventBusTests.js
  source/v1/cypress_tests/cypress/integration/tests/instructionTests.js
  source/v1/cypress_tests/cypress/integration/tests/keybindTests.js
  source/v1/cypress_tests/cypress/integration/tests/notificationTests.js
  source/v1/cypress_tests/cypress/integration/tests/settingsTests.js
  source/v1/cypress_tests/cypress/integration/tests/taskDisplayTests.js
  source/v1/cypress_tests/cypress/integration/tests/taskListTests.js
  source/v1/cypress_tests/cypress/integration/tests/taskTests.js
  source/v1/cypress_tests/cypress/integration/tests/themeTests.js
  source/v1/cypress_tests/cypress/integration/tests/timerContainerTests.js
  source/v1/cypress_tests/cypress/screenshots/tests/instructionTests.js/Instruction Box Tests -- Tests clicking to open and close instructions (failed).png
  source/v1/cypress_tests/cypress/screenshots/tests/keybindTests.js/Keybind Integration Tests -- Testing c (color change) (failed).png
  source/v1/cypress_tests/cypress/screenshots/tests/notificationTests.js/Notification Tests -- Test 1 cycle when permission is already granted (failed).png
  source/v1/cypress_tests/cypress/screenshots/tests/notificationTests.js/Notification Tests -- Test 1 cycle with asking permission (failed).png
  source/v1/cypress_tests/cypress/screenshots/tests/notificationTests.js/Notification Tests -- Test 1 cycle with notifs not allowed (failed).png
  source/v1/cypress_tests/cypress/screenshots/tests/notificationTests.js/Notification Tests -- Test notifs when resetting (failed).png
  source/v1/cypress_tests/cypress/screenshots/tests/taskDisplayTests.js/Task Display Tests -- Test Timer Display Functionality on Task Completion (failed).png
  source/v1/cypress_tests/cypress/screenshots/tests/taskListTests.js/Task List Tests -- Test showTaskList function being called correctly -- before each hook (failed).png
  source/v1/cypress_tests/cypress/screenshots/tests/themeTests.js/Theme Change Tests -- Tests clicking to toggle theme (failed).png
  source/v1/js/errorNotificationBox.js
  source/v1/js/eventBus.js
  source/v1/js/instructionsBox.js
  source/v1/js/main.js
  source/v1/js/settingsTab.js
Labels: bug, enhancement

#136 Feature/remove next task from showing when a session is active
  source/v1/jest_tests/taskDisplay.test.js
  source/v1/js/taskDisplay.js
Labels: enhancement

#137 fix timerContainer.test.js no window.alert and failing promise
  source/v1/jest_tests/timerContainer.test.js
  source/v1/js/notify.js
Labels: bug

#139 Feature/title status
  source/v1/jest_tests/timerContainer.test.js
  source/v1/js/timerContainer.js
Labels: enhancement

#140 fix pop_up error
  source/v1/js/eventBus.js
  source/v1/js/main.js
  source/v1/js/settingsTab.js
  source/v1/js/taskList.js
Labels: bug

#143 Update gen_docs.yml
  .github/workflows/gen_docs.yml
Labels: bug

#141 Docs/standups summaries
  .github/workflows/gen_docs.yml
  specifications/adrs/0029-open-tasklist-in-breaks.md
  specifications/adrs/0030-welcome-page.md
  specifications/meeting-summaries/06-01-wed.md
  specifications/meeting-summaries/06-05-sun.md
  specifications/standups/05-30-22.md
  specifications/standups/05-31-22.md
  specifications/standups/06-01-22.md
  specifications/standups/06-02-22.md
  specifications/standups/06-03-22.md
Labels: documentation

#144 addressed linting
  source/v1/js/errorNotificationBox.js
  source/v1/js/eventBus.js
  source/v1/js/instructionsBox.js
  source/v1/js/main.js
  source/v1/js/notify.js
  source/v1/js/settingsTab.js
  source/v1/js/timerContainer.js
  source/v1/js/welcomeBox.js
Labels: bug

#147 Fix/merge conflict
  source/v1/cypress_tests/cypress/integration/tests/taskTests.js
Labels: bug

#148 Fixed some cypress tests with next
  .github/workflows/gen_docs.yml
  source/v1/cypress_tests/cypress/integration/tests/eventBusTests.js
  source/v1/cypress_tests/cypress/integration/tests/keybindTests.js
  source/v1/cypress_tests/cypress/integration/tests/taskDisplayTests.js
  source/v1/js/taskDisplay.js
Labels: bug

#153 Fix/pomo image render
  source/js/timer.js
Labels: bug

#167 Fix a typo in Error Notification Box
  source/js/errorNotificationBox.js
Labels: bug

#169 Fix Typo
  source/js/errorNotificationBox.js
Labels: bug

#170 End of Sprint Merge to Main
  source/js/errorNotificationBox.js
Labels: enhancement
