Repository yitianwang18/cse112-s22-group14, pull requests merged in 2022-05, with the labels that each got.

#16 fix Safari No Audio Issue
  source/v1/js/notify.js
Labels: bug

#23 Feature/eslint style rules
  .github/linters/.eslintrc.yml
Labels: enhancement

#22 Fix: fix subdirectory path matching issue in workflows
  .github/workflows/build-dev.yml
  .github/workflows/firebase-hosting-pull-request.yml
  .github/workflows/jest.yml
  .github/workflows/lint.yml
Labels: bug

#31 Fix/sync dev with main workflow
  .github/workflows/build-dev.yml
  .github/workflows/firebase-hosting-pull-request.yml
  .github/workflows/jest.yml
  .github/workflows/lint.yml
Labels: bug

#40 updated themes, logos, task list, and instr box
  source/v1/assets/img/PomoHeroLogo2_120x.png
  source/v1/assets/img/PomoTitleA-500x.png
  source/v1/assets/img/PowelldoroLogo.png
  source/v1/assets/img/PowelldoroWords.png
  source/v1/css/layout.css
  source/v1/index.html
  source/v1/js/instructionsBox.js
  source/v1/js/taskList.js
Labels: enhancement

#30 added timer display to browser title
  .gitignore
  source/v1/js/timerContainer.js
Labels: enhancement

#47 created settings tab and its UI
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/notify.js.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov-report/task.js.html
  coverage/lcov-report/taskDisplay.js.html
  coverage/lcov-report/taskList.js.html
  coverage/lcov-report/timer.js.html
  coverage/lcov-report/timerContainer.js.html
  coverage/lcov.info
  source/v1/css/colors-dark.css
  source/v1/css/colors-forest.css
  source/v1/css/layout.css
  source/v1/index.html
  source/v1/js/eventBus.js
  source/v1/js/main.js
  source/v1/js/settingsTab.js
  source/v1/js/taskList.js
Labels: enhancement

#54 UI - Safari error notification view
  source/v1/css/layout.css
  source/v1/index.html
  source/v1/js/errorNotificationBox.js
  source/v1/js/main.js
  source/v1/js/notify.js
Labels: bug

#58 update JSDoc workflow and fix a JSDoc error
  .github/workflows/gen_docs.yml
  source/v1/js/taskDisplay.js
Labels: documentation

#60 Fix/js docs
  .github/workflows/gen_docs.yml
Labels: documentation

#75 Update TaskList E2E Cypress Tests
  source/v1/cypress_tests/cypress/integration/tests/taskListTests.js
Labels: enhancement

#73 finish task tests and local storage tests
  source/v1/cypress_tests/cypress/integration/tests/taskTests.js
Labels: enhancement

#72 Feature/add safari error notifi checkbox
  source/v1/css/layout.css
  source/v1/js/notify.js
  source/v1/js/settingsTab.js
Labels: enhancement

#76 2nd theme, pop-up colors, drag UI, cons. log bool
  .github/workflows/lint.yml
  coverage/clover.xml
  coverage/coverage-final.json
  coverage/lcov-report/base.css
  coverage/lcov-report/block-navigation.js
  coverage/lcov-report/favicon.png
  coverage/lcov-report/index.html
  coverage/lcov-report/notify.js.html
  coverage/lcov-report/prettify.css
  coverage/lcov-report/prettify.js
  coverage/lcov-report/sort-arrow-sprite.png
  coverage/lcov-report/sorter.js
  coverage/lcov-report/task.js.html
  coverage/lcov-report/taskDisplay.js.html
  coverage/lcov-report/taskList.js.html
  coverage/lcov-report/timer.js.html
  coverage/lcov-report/timerContainer.js.html
  coverage/lcov.info
  source/v1/assets/img/PomoCountNo2.png
  source/v1/assets/img/PomoCountYes2.png
  source/v1/assets/img/bground/bg2-1280w.webp
  source/v1/assets/img/bground/bg2-1920w.webp
  source/v1/assets/img/bground/bg2-2560w.webp
  source/v1/assets/img/bground/bg2-3840w.webp
  source/v1/assets/img/bground/bg2-640w.webp
  source/v1/css/colors-dark.css
  source/v1/css/colors-forest.css
  source/v1/css/colors-stars.css
  source/v1/css/layout.css
  source/v1/index.html
  source/v1/js/errorNotificationBox.js
  source/v1/js/eventBus.js
  source/v1/js/instructionsBox.js
  source/v1/js/main.js
  source/v1/js/notify.js
  source/v1/js/task.js
  source/v1/js/taskDisplay.js
  source/v1/js/taskList.js
  source/v1/js/timer.js
  source/v1/js/timerContainer.js
Labels: enhancement

#88 Fix Error Messages
  source/v1/css/colors-forest.css
  source/v1/css/colors-stars.css
  source/v1/css/layout.css
  source/v1/cypress_tests/cypress/integration/tests/errorMessagesTests.js
  source/v1/jest_tests/taskList.test.js
  source/v1/js/eventBus.js
  source/v1/js/taskList.js
  source/v1/js/timerContainer.js
Labels: enhancement

#80 Feature/timer customization
  package-lock.json
  package.json
  source/v1/jest_tests/task.test.js
  source/v1/jest_tests/taskList.test.js
  source/v1/jest_tests/timer.test.js
  source/v1/jest_tests/timerContainer.test.js
  source/v1/js/settingsTab.js
  source/v1/js/task.js
  source/v1/js/taskList.js
  source/v1/js/timer.js
  source/v1/js/timerContainer.js
Labels: enhancement

#79 Fix/close button popping up
  source/v1/js/eventBus.js
  source/v1/js/taskList.js
Labels: bug

#86 Fix/increase accessibility
  source/v1/css/layout.css
  source/v1/index.html
  source/v1/js/instructionsBox.js
  source/v1/js/main.js
  source/v1/js/settingsTab.js
  source/v1/js/taskList.js
  source/v1/js/timerContainer.js
Labels: bug

#87 settings fit on mobile
  source/v1/css/layout.css
Labels: enhancement

#90 add jest tests for notify.js and fix spelling error
  .github/linters/.eslintrc.yml
  source/v1/jest_tests/notify.test.js
  source/v1/js/notify.js
Labels: bug, enhancement

#67 Added New ADRs
  specifications/adrs/0022-second-theme.md
  specifications/adrs/0023-safari-notification-permissions.md
  specifications/adrs/0024-visual-timer.md
  specifications/meeting-summaries/05-15-sun.md
Labels: documentation

#93 Fixed Linting issues
  source/v1/css/colors-forest.css
  source/v1/css/colors-stars.css
  source/v1/css/layout.css
  source/v1/jest_tests/notify.test.js
  source/v1/jest_tests/taskList.test.js
  source/v1/jest_tests/timerContainer.test.js
  source/v1/js/errorNotificationBox.js
  source/v1/js/eventBus.js
  source/v1/js/notify.js
  source/v1/js/settingsTab.js
  source/v1/js/task.js
  source/v1/js/taskDisplay.js
  source/v1/js/taskList.js
  source/v1/js/timer.js
  source/v1/js/timerContainer.js
Labels: enhancement

#94 added JSDoc
  docs/EventBus.html
  docs/InstructionsBox.html
  docs/NotificationBox.html
  docs/SettingsTab.html
  docs/Task.html
  docs/TaskDisplay.html
  docs/TaskList.html
  docs/TimerContainer.html
  docs/TimerDisplay.html
  docs/cypress_tests_cypress_plugins_index.js.html
  docs/fonts/OpenSans-Bold-webfont.eot
  docs/fonts/OpenSans-Bold-webfont.svg
  docs/fonts/OpenSans-Bold-webfont.woff
  docs/fonts/OpenSans-BoldItalic-webfont.eot
  docs/fonts/OpenSans-BoldItalic-webfont.svg
  docs/fonts/OpenSans-BoldItalic-webfont.woff
  docs/fonts/OpenSans-Italic-webfont.eot
  docs/fonts/OpenSans-Italic-webfont.svg
  docs/fonts/OpenSans-Italic-webfont.woff
  docs/fonts/OpenSans-Light-webfont.eot
  docs/fonts/OpenSans-Light-webfont.svg
  docs/fonts/OpenSans-Light-webfont.woff
  docs/fonts/OpenSans-LightItalic-webfont.eot
  docs/fonts/OpenSans-LightItalic-webfont.svg
  docs/fonts/OpenSans-LightItalic-webfont.woff
  docs/fonts/OpenSans-Regular-webfont.eot
  docs/fonts/OpenSans-Regular-webfont.svg
  docs/fonts/OpenSans-Regular-webfont.woff
  docs/global.html
  docs/index.html
  docs/js_errorNotificationBox.js.html
  docs/js_eventBus.js.html
  docs/js_instructionsBox.js.html
  docs/js_main.js.html
  docs/js_notify.js.html
  docs/js_settingsTab.js.html
  docs/js_task.js.html
  docs/js_taskDisplay.js.html
  docs/js_taskList.js.html
  docs/js_timer.js.html
  docs/js_timerContainer.js.html
  docs/scripts/linenumber.js
  docs/scripts/prettify/Apache-License-2.0.txt
  docs/scripts/prettify/lang-css.js
  docs/scripts/prettify/prettify.js
  docs/styles/jsdoc-default.css
  docs/styles/prettify-jsdoc.css
  docs/styles/prettify-tomorrow.css
Labels: documentation
